# Assignment Set 1 - Module Creating Arrays And Solution:

In [ ]:
import numpy as np

### Q1.  Create a 2x2x2 3-D array containing total 8 elements.

In [ ]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Q2.  Replace the 1st element of the above 3-D array with 10

In [ ]:
arr_3d[0,0,0] = 10
arr_3d

array([[[10,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

### 3.  Check the shape and dimensions of the above 3-D array

In [ ]:
print('shape :',arr_3d.shape)
print('dimensions :',arr_3d.ndim)

shape : (2, 2, 2)
dimensions : 3


### 4. Export the above array

In [ ]:
np.save('output.npy', arr_3d)

### 5. Import the array from given url

``` url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' ```

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

data = np.genfromtxt(url,delimiter=',', dtype='float')
data