In [2]:
import numpy as np

**Create 3x2 array**

In [18]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
arr.shape

(3, 2)

**Reshape it to 2X3 form**

In [21]:
arr2 = arr.reshape(2, 3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(id(arr))
print(id(arr2))

140446771961456
140446771990224


**If we don't know the number of rows but know the column before hand, set n_rows=-1**

In [23]:
arr = np.arange(69)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68])

In [24]:
arr.reshape(-1, 3)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
        39, 40, 41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68]])

**`resize()` changes the shape of array in place. No need to reassign**

In [25]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
id(arr)

140446771492976

In [27]:
arr.resize(5, 3)

In [28]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
id(arr)

140446771492976

**Add an axis: column or row**

In [33]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [35]:
# make it as a column of a 2d array
arr1 = arr[:, np.newaxis]
arr1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
arr1.shape

(5, 1)

In [37]:
# make it as a row of 2d array
arr2 = arr[np.newaxis, :]
arr2

array([[0, 1, 2, 3, 4]])

In [39]:
arr2.shape

(1, 5)

**Flatten an array**<br>
Flattens an array by creating a new copy of it

In [40]:
arr = np.array([[1, 2],[3, 4],[5, 6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
a2 = arr.flatten()
a2

array([1, 2, 3, 4, 5, 6])

In [42]:
print(id(arr))
print(id(a2))

140446627760336
140446627745008


**Ravel**<br>
Ravel doesn't create a new array. It is a flattened view of the original one.

In [43]:
a3 = arr.ravel()

In [44]:
id(arr)  # same id as arr. so same as 'arr'

140446627760336

In [45]:
id(a3)

140446627601648

In [46]:
a3

array([1, 2, 3, 4, 5, 6])

In [47]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

Use `arr.flat()` to iterate

In [48]:
for element in  arr.flat:
  print(element)

1
2
3
4
5
6


**Practice cahllenge**<br>
Reshape the given array to a 2D array containing 4 rows. Try to do as if we don't know the no. of columns needed.
<br><br>
&nbsp;&nbsp;ar = np.arange(24)

In [51]:
# given
ar = np.arange(24)

print(ar)
print(ar.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)


In [52]:
# solution
arr_reshaped = ar.reshape(4, -1)
arr_reshaped

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
arr_reshaped.shape

(4, 6)