**Create a simple sequence**

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Sequence with steps**

In [2]:
# steps of 3
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

Reverse direction with negative step

In [3]:
np.arange(20, 1, -3)

array([20, 17, 14, 11,  8,  5,  2])

**When we don't know the step size**<br>
Use `np.linspace` Linear and equally sapces sequence.

In [4]:
np.linspace(1, 2, 10) # here we know no. of items, i.e: 10

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

To see the stepsize used, set `retstep=True`

In [5]:
np.linspace(1, 2, 10, retstep=True)

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

**Log Space**<br>
Similar to `linspace` but in log

In [6]:
# log values: log(10) = 1 to log(100) = 2
np.logspace(1, 2, 10)

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

**Repeating Sequences** <br>
`np.tile(x, n)` will repeat sequence `x`, `n` times

In [7]:
np.tile([1,2,3,4], 3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

Repeat each item n times

In [8]:
np.repeat([1,2,3,4], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

**Practise challenge**<br>
Calculate the following pattern using the following input, without typing the  sequence itself. <br>
**Input**:<br>
a = np.array([1,2,3])<br>
**Output**:<br>
array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
a = np.array([1,2,3])

# solution 1:*
output = np.concatenate((np.repeat(a, 3) , np.tile(a, 3)))
output                             

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
# solution 2:
np.array([np.repeat(a, 3), np.tile(a, 3)]).flatten()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])