**Broadcasting**<br>We previously saw how NumPy's universal functions can be used to vectorize operations and thereby remove slow Python loops. Another means of vectorizing operations is to use NumPy's broadcasting functionality.
1. Broadcasting is the ability of NumPy to treat arrays of different shapes during mathematical operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes. <br>
2. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python as we know that Numpy implemented in C. <br>
3. It does this without making needless copies of data and which leads to efficient algorithm implementations.

In [ ]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Recall that for the array of the same size operations are performed on an element-by-element basis

In [ ]:
a = np.array([0, 1, 2])
b = np.array([7, 7, 7])
a + b

array([7, 8, 9])

Broadcast multiplication by 3 to all elements of arr

In [ ]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

<img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'></img>

**2D Example**

In [ ]:
arr_2d = np.random.randint(1, 12, size=(5, 3))
arr_2d

array([[ 7,  7, 10],
       [ 7,  7,  2],
       [ 8,  8, 11],
       [10,  5,  4],
       [ 3,  2,  8]])

In [ ]:
mean_cols = arr_2d.mean(axis=0)
mean_cols

array([7. , 5.8, 7. ])

Let us subtract the mean from every row, we can simply do that though the array shape differ.<br>
 **Numpy takes care of how to align the axis automatically and broadcast it.**

In [ ]:
arr_2d - mean_cols

array([[ 0. ,  1.2,  3. ],
       [ 0. ,  1.2, -5. ],
       [ 1. ,  2.2,  4. ],
       [ 3. , -0.8, -3. ],
       [-4. , -3.8,  1. ]])

**Subtract row means** <br>
For this, we need to explicitly reshape `mean_rows` to align vertically with `arr_2d` and then perform subtraction.

In [ ]:
mean_rows = arr_2d.mean(axis=1)
mean_rows

array([8.        , 5.33333333, 9.        , 6.33333333, 4.33333333])

In [ ]:
# # won't work
# arr_2d - mean_rows

In [ ]:
arr_2d - mean_rows.reshape(5,1)

array([[-1.        , -1.        ,  2.        ],
       [ 1.66666667,  1.66666667, -3.33333333],
       [-1.        , -1.        ,  2.        ],
       [ 3.66666667, -1.33333333, -2.33333333],
       [-1.33333333, -2.33333333,  3.66666667]])

`logaddexp(a, b)` function, which computes `log(exp(a) + exp(b))` with more precision than the naive approach:

In [ ]:
np.logaddexp(np.arange(9).reshape(3,3), np.arange(9).reshape(3,3))

array([[0.69314718, 1.69314718, 2.69314718],
       [3.69314718, 4.69314718, 5.69314718],
       [6.69314718, 7.69314718, 8.69314718]])

**Practice Challenge**<br>
Scale every row of below 2D array. i.e: Subtract each row by its mean and then divide by its standard deviation. Doing so, the resultant row should have mean=0 and s.d.=1


In [2]:
import numpy as np
np.random.seed(100)
x = np.random.random((10, 7)).round(3)
x

array([[0.543, 0.278, 0.425, 0.845, 0.005, 0.122, 0.671],
       [0.826, 0.137, 0.575, 0.891, 0.209, 0.185, 0.108],
       [0.22 , 0.979, 0.812, 0.172, 0.816, 0.274, 0.432],
       [0.94 , 0.818, 0.336, 0.175, 0.373, 0.006, 0.252],
       [0.796, 0.015, 0.599, 0.604, 0.105, 0.382, 0.036],
       [0.89 , 0.981, 0.06 , 0.891, 0.577, 0.742, 0.63 ],
       [0.582, 0.02 , 0.21 , 0.545, 0.769, 0.251, 0.286],
       [0.852, 0.975, 0.885, 0.36 , 0.599, 0.355, 0.34 ],
       [0.178, 0.238, 0.045, 0.505, 0.376, 0.593, 0.63 ],
       [0.143, 0.934, 0.946, 0.602, 0.388, 0.363, 0.204]])

In [20]:
mean_rows = np.mean(x, 1).reshape(-1, 1)
std_rows = np.std(x, 1).reshape(-1, 1)
x_centered = x - mean_rows
x_centered

array([[ 0.13028571, -0.13471429,  0.01228571,  0.43228571, -0.40771429,
        -0.29071429,  0.25828571],
       [ 0.40728571, -0.28171429,  0.15628571,  0.47228571, -0.20971429,
        -0.23371429, -0.31071429],
       [-0.30928571,  0.44971429,  0.28271429, -0.35728571,  0.28671429,
        -0.25528571, -0.09728571],
       [ 0.52571429,  0.40371429, -0.07828571, -0.23928571, -0.04128571,
        -0.40828571, -0.16228571],
       [ 0.43357143, -0.34742857,  0.23657143,  0.24157143, -0.25742857,
         0.01957143, -0.32642857],
       [ 0.20842857,  0.29942857, -0.62157143,  0.20942857, -0.10457143,
         0.06042857, -0.05157143],
       [ 0.20157143, -0.36042857, -0.17042857,  0.16457143,  0.38857143,
        -0.12942857, -0.09442857],
       [ 0.22828571,  0.35128571,  0.26128571, -0.26371429, -0.02471429,
        -0.26871429, -0.28371429],
       [-0.18842857, -0.12842857, -0.32142857,  0.13857143,  0.00957143,
         0.22657143,  0.26357143],
       [-0.36842857,  0.4225

In [24]:
x_scaled = x_centered / std_rows
x_scaled.round(3)

array([[ 0.469, -0.485,  0.044,  1.557, -1.468, -1.047,  0.93 ],
       [ 1.299, -0.899,  0.499,  1.507, -0.669, -0.746, -0.991],
       [-1.005,  1.462,  0.919, -1.162,  0.932, -0.83 , -0.316],
       [ 1.665,  1.279, -0.248, -0.758, -0.131, -1.293, -0.514],
       [ 1.486, -1.19 ,  0.811,  0.828, -0.882,  0.067, -1.118],
       [ 0.724,  1.04 , -2.158,  0.727, -0.363,  0.21 , -0.179],
       [ 0.84 , -1.502, -0.71 ,  0.686,  1.619, -0.539, -0.393],
       [ 0.884,  1.361,  1.012, -1.021, -0.096, -1.041, -1.099],
       [-0.917, -0.625, -1.565,  0.675,  0.047,  1.103,  1.283],
       [-1.215,  1.394,  1.434,  0.299, -0.407, -0.49 , -1.014]])

In [25]:
# check if mean = 0 and s.d. = 1
print("row mean = ", x_scaled.mean(1).round(3))
print("row mean = ", x_scaled.std(1))

row mean =  [-0. -0.  0.  0. -0. -0.  0.  0. -0.  0.]
row mean =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
