<h3><b><center>Matrix Operations</h3></b></center>

In [1]:
import numpy as np

In [2]:
np.random.seed(109)
X = np.arange(9).reshape(3,3)
Y = np.random.randint(0, 9, (3, 3))

print('X: \n', X)
print('Y: \n', Y)

X: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Y: 
 [[6 5 5]
 [0 1 4]
 [3 0 2]]


**Dot Product** <br>
Multiplies row of first matrix with corresponding column of second matrix for each element

In [3]:
# dot product
np.dot(X, Y)

array([[ 6,  1,  8],
       [33, 19, 41],
       [60, 37, 74]])

In [4]:
# another notation for dot prod
X @ Y

array([[ 6,  1,  8],
       [33, 19, 41],
       [60, 37, 74]])

**Element wise multiplication - Hadamard Product**

In [5]:
X * Y

array([[ 0,  5, 10],
       [ 0,  4, 20],
       [18,  0, 16]])

In [6]:
# alternate
np.multiply(X, Y)

array([[ 0,  5, 10],
       [ 0,  4, 20],
       [18,  0, 16]])

**Inverse of a matrix** <br>
The inverse of a matrix A is a matrix which, on dot product with A results in the identity matrix. The mathematical notation for this inverse matrix is A<sup>–1</sup>.

In [7]:
Y_inverse = np.linalg.inv(Y)
Y_inverse

array([[ 0.03508772, -0.1754386 ,  0.26315789],
       [ 0.21052632, -0.05263158, -0.42105263],
       [-0.05263158,  0.26315789,  0.10526316]])

In [8]:
Y_inverse @ Y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

An inverse of a matrix exists only if the determinant of a matrix is non-zero. So, trying to compute an inverse of X is not possible. Such type of matrix with det. zero is called `Singular Matrix`

In [9]:
np.linalg.det(X)

0.0

In [11]:
# won't work
# np.linalg.inv(X)

**Derterminant of a matrix** <br>


In [14]:
mat = np.array([[5, 6],
             [7, 8]])

np.linalg.det(mat)

-2.000000000000005

In [15]:
# calculation (ad - bc)
(5 * 8) - (6 * 7)

-2

**Rank of a matrix**<br>
Rank of a matrix is the maximum number of its linearly independent rows (or columns).Linear Independence is one if no column (row) of a matrix can be written as linear combination of other columns (rows).

In [16]:
mat

array([[5, 6],
       [7, 8]])

In [17]:
np.linalg.matrix_rank(mat)

2

**Example 2**

In [22]:
mat2 = np.array([[4, 5, 6],
                 [8, 11, 13],
                 [-1, 6, 12]])

print('Rank of mat2 = ',np.linalg.matrix_rank(mat2) )

Rank of mat2 =  3


**Power of a Matrix** <br>
Raising n<sup>th</sup> power to a matrix

In [24]:
np.linalg.matrix_power(mat, 3)

array([[ 881, 1026],
       [1197, 1394]])

In [26]:
mat @ mat @ mat

array([[ 881, 1026],
       [1197, 1394]])

**Eigern Values and Eigen Vectors**<br>
The number `w` is an eigenvalue of `a` if there exists a vector `v` such that `a @ v = w * v `.

In [29]:
# eigen values
arr = np.array([[7, 2, 2],
                [5, -3, 6],
                [2, 10, 8]])

print('Array : \n', arr)

# calculating an eigen value,vector
w, v = np.linalg.eig(arr)

print('\n Eigen Value : \n', w)
print('\n Eigen Vector : \n', v)

Array : 
 [[ 7  2  2]
 [ 5 -3  6]
 [ 2 10  8]]

 Eigen Value : 
 [13.76940212  5.39376107 -7.16316319]

 Eigen Vector : 
 [[-0.36753595 -0.77485675  0.04098905]
 [-0.40851647 -0.00975899 -0.83657863]
 [-0.83548286  0.63206153  0.54631135]]


**Check**

In [41]:
w * v

array([[False, False, False],
       [False, False,  True],
       [False, False, False]])

In [33]:
arr @ v

array([[ -5.06075035,  -4.17939218,  -0.29361123],
       [ -5.62502755,  -0.05263764,   5.99254924],
       [-11.50409952,   3.40918886,  -3.91331737]])

**QR Decomosition** <br>
Also called factorization, is a decomposition of a matrix A into a product `A = Q.R` of an orthogonal matrix Q and an upper triangular matrix R.

In [37]:
arr = np.array([[7, 2, 2],
                [5, -3, 6],
                [2, 10, 8]])

arr

array([[ 7,  2,  2],
       [ 5, -3,  6],
       [ 2, 10,  8]])

In [38]:
q, r = np.linalg.qr(arr)

print('Q :', q, '\n')
print('R :', r, '\n')

Q : [[-0.79259392  0.02832534 -0.60909158]
 [-0.56613852 -0.40517549  0.71785793]
 [-0.22645541  0.91380003  0.33717569]] 

R : [[-8.83176087 -2.15132636 -6.7936622 ]
 [ 0.         10.41017747  4.93599802]
 [ 0.          0.          5.78636996]] 



**Check** <br>
Dot product of q and r results an original matrix .

In [40]:
q @ r  # equals arr

array([[ 7.,  2.,  2.],
       [ 5., -3.,  6.],
       [ 2., 10.,  8.]])

**Single Value Decomposition (SVD)**<br>
Decompose a given matrix into its 3 constituent matrices P, D and Q.

In [42]:
x = np.random.normal(size=[10, 6])
x

array([[-0.17768802, -0.83874355, -0.15628712, -0.34176163,  0.81873029,
        -0.09261394],
       [ 0.50808094, -1.7542225 , -0.36481798, -0.03091855, -0.12614427,
         0.299181  ],
       [ 1.82207405,  1.41717686, -0.45731622,  0.86019957,  0.28468256,
         0.51062749],
       [ 1.57829456,  0.16130871,  0.71819658, -0.80599584, -0.59818081,
         1.32383635],
       [ 1.13726714, -0.48833019,  0.34806743, -0.97086135, -0.21213643,
         0.42335106],
       [ 0.10377004,  0.05097481, -0.67144065,  0.27170251,  0.00701349,
         0.32662299],
       [ 0.03618145, -1.19327841, -0.15810171,  0.01341776, -0.47234681,
        -0.20810645],
       [ 1.44154411, -1.67109527,  0.54455933,  1.26132175,  0.96283701,
        -0.27990168],
       [-0.23044776,  0.45213427, -0.35421077,  0.34015305,  0.63620222,
         0.75003234],
       [ 1.3507378 , -0.28858894,  0.08703628, -0.08413142, -0.99903647,
         0.10133759]])

In [47]:
P, D, Q = np.linalg.svd(x, full_matrices=False)

In [48]:
print(P.shape)
print(D.shape)
print(Q.shape)

(10, 6)
(6,)
(6, 6)


In [50]:
x_svd = P @ np.diag(D) @ Q
x_svd

array([[-0.17768802, -0.83874355, -0.15628712, -0.34176163,  0.81873029,
        -0.09261394],
       [ 0.50808094, -1.7542225 , -0.36481798, -0.03091855, -0.12614427,
         0.299181  ],
       [ 1.82207405,  1.41717686, -0.45731622,  0.86019957,  0.28468256,
         0.51062749],
       [ 1.57829456,  0.16130871,  0.71819658, -0.80599584, -0.59818081,
         1.32383635],
       [ 1.13726714, -0.48833019,  0.34806743, -0.97086135, -0.21213643,
         0.42335106],
       [ 0.10377004,  0.05097481, -0.67144065,  0.27170251,  0.00701349,
         0.32662299],
       [ 0.03618145, -1.19327841, -0.15810171,  0.01341776, -0.47234681,
        -0.20810645],
       [ 1.44154411, -1.67109527,  0.54455933,  1.26132175,  0.96283701,
        -0.27990168],
       [-0.23044776,  0.45213427, -0.35421077,  0.34015305,  0.63620222,
         0.75003234],
       [ 1.3507378 , -0.28858894,  0.08703628, -0.08413142, -0.99903647,
         0.10133759]])

In [51]:
print('Is x and x_svd close? ', np.isclose(x, x_svd).all())

Is x and x_svd close?  True
