**Solving Linear Equations:** <br>
The Numpy library contains the `linalg.solve()` method, which can be used to directly find the solution of a system of linear equations:

Let's solve a system of three linear equations, as shown below:

4x + 3y + 2z = 25 <br>
-2x + 2y + 3z = -10 <br>
3x -5y + 2z = -4 <br>

**Three variables example**:

In [8]:
import numpy as np

# coefficients 
A = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])

# constants
b = np.array([25, -10, -4])

**Solve**

In [9]:
x = np.linalg.solve(A, b)
print('SOLUTION \n', x)

SOLUTION 
 [ 5.  3. -2.]


**Check** <br>
<pre>we know, i) A.x = b 
         ii) x = A<sup>-1</sup>.b
</pre>

In [10]:
# i) => b
np.dot(A, x)

array([ 25., -10.,  -4.])

In [11]:
# ii) => x
np.linalg.inv(A).dot(b)  

array([ 5.,  3., -2.])

**A Real-World Example** <br>
Let's see how a system of linear equation can be used to solve real-world problems.<br>

Suppose, a fruit-seller sold 30 mangoes and 12 oranges in one day for a total of Rs.480. The next day he sold 13 mangoes and 27 oranges for Rs.535. If the prices of the fruits remained unchanged on both the days, what was the price of one mango and one orange?<br>

This problem can be easily solved with a system of two linear equations.

let price of one mango is x and the price of one orange is y. <br>
Conversion:<br>
30x + 12y = 350 <br>
13x + 27y = 500

In [20]:
# coeff
A = np.array([[30, 12], [13, 27]])

# const.
b = np.array([480, 535])

**Solution**

In [21]:
x = np.linalg.solve(A, b)

print("Solution : ", x)

Solution :  [10. 15.]


**Check**

In [22]:
np.dot(A, x)

array([480., 535.])