# Assignment 2 On Data Manipulation With Solution:

In [ ]:
import numpy as np

### 1. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10. 

In [ ]:
# solution method 1
arr_2d = np.random.randint(5,10, (5, 3)) + np.random.random((5, 3))
arr_2d

array([[5.94793144, 6.89733563, 7.87168406],
       [7.69467667, 5.41920345, 6.65702105],
       [6.50245758, 6.32884758, 9.41859688],
       [5.47971031, 6.15246714, 7.21174767],
       [9.32334372, 6.18836579, 6.16764739]])

In [ ]:
# Solution method 2
arr_2d = np.random.uniform(5, 10, (5, 3))
arr_2d

array([[5.62176605, 7.18699518, 8.57283503],
       [8.80050079, 7.577333  , 6.78882023],
       [7.41978264, 7.26843116, 6.08774986],
       [9.27132276, 5.62162567, 5.17333534],
       [5.84522258, 5.46693341, 9.60291199]])

### 2. Insert np.nan values at 20 random positions in iris_2d dataset

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```



In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# solution method 1
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
iris_2d

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# solution method 2
i, j = np.where(iris_2d)

np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

iris_2d

### 3.  Find out if iris_2d has any missing values

``` 
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
````


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()       # True or False

False

### 4.  Find the number and position of missing values in iris_2d's sepallength (1st column)

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values = ", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values = ", np.where(np.isnan(iris_2d[:, 0])))


Number of missing values =  4
Position of missing values =  (array([  0,  71,  84, 138]),)


### 5. Select the rows of iris_2d that does not have any nan value.

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

```

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution 1
iris_2d[~np.isnan(iris_2d).any(axis=1), :]

In [ ]:
# Solution 2
is_nan_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[is_nan_row]

### 6. Find mean of every row in iris_2d array

```
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

````

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan 

np.nanmean(iris_2d, axis=1)

### 7. Get the common items between a and b

```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

### 8. From array a remove all items present in array b

```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

array([1, 2, 3, 4])