**Searchsorted and Bisect**<br>
when trying to insert a number in a sorted array, `Searchsorted` finds the position that will keep the array in sorted order.

In [13]:
import numpy as np
np.set_printoptions(threshold=2000)

In [14]:
np.random.seed(100)
a = np.random.randint(1, 100, size=1000)
a.sort()

In [ ]:
a

In [16]:
num = 7
pos = np.searchsorted(a, num)
pos

56

If `side=right`, return the last such index

In [17]:
np.searchsorted(a, num, side='right')

61

Insert in element by reconstructing the array

In [18]:
a1 = np.r_[a[:pos], num, a[pos:]]
a1[:100]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11])

In [20]:
np.searchsorted(a, [7, 65, 50, 90])

array([ 56, 637, 476, 894])

In [23]:
%%timeit
np.searchsorted(a, [7, 65, 50, 90])

The slowest run took 190.45 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.06 µs per loop


**Bisect Module**<br>
The bisect module provides a similar functionality as what `np.searchsorted` achieves. That is, it helps keeping a list in the sorted order after inserting a number without having to re-sort it.

In [28]:
import bisect

In [29]:
np.random.seed(100)
a = np.random.randint(1, 100, size=1000)
a.sort()

In [30]:
a[:100]

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  6,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11])

In [31]:
num = 7
bisect.bisect(a, num)

61

In [32]:
bisect.bisect_left(a, num)

56

`bisect.insort_left` will insert the number at the earliest position to keep the list sorted. Likewise `bisect.insort_right` will insert at the latest position.

In [33]:
a = a.tolist()
bisect.insort_left(a, num)

In [35]:
print(a[:100])

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11]


**Practice Challenge**<br>
A student grade as per marks are shown below:<br>
`>90 -> A`<br>
`>80 -> B`<br>
`>50 -> C`<br>
`>30 -> D`<br>
`<=30 -> E`<br>
Use np.searchsorted to obtain the grades for the scores : 21, 36, 43, 58, 84, 98
<br><br>
Expected Output: <br>
-> ['E', 'D', 'D', 'C', 'B', 'A']


In [44]:
import numpy as np

def find_grade(score, breaks=[30, 50, 80, 90], grades='EDCBA'):
  i = np.searchsorted(breaks, score)
  return grades[i]

[find_grade(score) for score in [21, 36, 43, 58, 84, 98]]

['E', 'D', 'D', 'C', 'B', 'A']