<center><h2><strong>Vectorization</strong><h2></center>

with the help of **vectorize()** we can make a function that is meant to work on individual numbers, to work on arrays.
<br>
The function `prime_or_not` accepts a number and check if it is a prime number. When we apply this function on scalar(individual number) it works perfectly, but fails when applied on an array or a list. <br>
Whereas numpy vectorize func can work on list or array. Nice!

In [1]:
import numpy as np

In [2]:
def prime_or_not(num):
  if num > 1:
    for i in range(2, num):
      if (num % i) == 0:
        return False
      else:
        return True

# on a scalar
print('is 20 prime?', prime_or_not(20))
print('is 13 prime?', prime_or_not(13))

is 20 prime? False
is 13 prime? True


**Calling same on an array or list it won't work**

In [3]:
# # won't work !
# prime_or_not([17, 18, 19, 20])  # # ERROR

**Let's see the beauty of `np.vectorize`**

In [4]:
prime_or_not_v = np.vectorize(prime_or_not)

works on scalar

In [5]:
print('is 20 prime?', prime_or_not_v(20))
print('is 13 prime?', prime_or_not_v(13))
print('is 17 prime?', prime_or_not_v(17))

is 20 prime? False
is 13 prime? True
is 17 prime? True


works with vector as well!

In [6]:
prime_or_not_v([17, 18, 19, 20])

array([ True, False,  True, False])

Specify the type of the output to make in `otypes`

In [7]:
prime_or_not_o = np.vectorize(prime_or_not, otypes=[bool])  # explicitly mentioning output type

Run on scalars

In [8]:
print('is 20 prime?', prime_or_not_o(20))
print('is 13 prime?', prime_or_not_o(13))
print('is 17 prime?', prime_or_not_o(17))

is 20 prime? False
is 13 prime? True
is 17 prime? True


Runs on vector

In [9]:
prime_or_not_o([17, 18, 19, 20])

array([ True, False,  True, False])

**Practice Challenge**<br>
Vectorize the `find_profit` func to make it work for all rows of the dataset.<br>
<pre>
def find_profit(open, high, low, close):
  buy = open * 0.999
  if low < buy < high:
    return (close - buy) / buy
  else:
    return 0

# data to read
arr = np.genfromtxt("Datasets/apple_price.csv", delimiter = ',', skip_header = 1)
</pre>


In [10]:
def find_profit(open, high, low, close):
  buy = open * 0.999
  if low < buy < high:
    return (close - buy) / buy
  else:
    return 0

In [11]:
# data to read
arr = np.genfromtxt("Datasets/apple_stock_price.csv", delimiter = ',', skip_header = 1)
arr

array([[127.489998, 128.880005, 126.919998, 127.830002],
       [127.629997, 128.779999, 127.449997, 128.720001],
       [128.479996, 129.029999, 128.330002, 128.449997],
       ...,
       [133.470001, 135.089996, 133.25    , 135.020004],
       [135.520004, 136.270004, 134.619995, 135.509995],
       [135.669998, 135.899994, 134.839996, 135.350006]])

In [15]:
find_profit(127.629997, 128.779999, 127.449997, 128.720001)

0.009549893273521293

**Solution: Vectorize**

In [13]:
find_profit_v = np.vectorize(find_profit, otypes=[float])

In [14]:
result = find_profit_v(arr[:, 0], arr[:, 1], arr[:, 2], arr[:, 3])
result[:10]

array([ 0.00367058,  0.00954989,  0.00076728,  0.00784975,  0.02394346,
       -0.00479691, -0.02007515,  0.01366997, -0.01085696, -0.00023818])