In [42]:
import numpy as np

dt = np.dtype([("Manufacturer", np.unicode_, 16),
               ("Model", np.unicode_, 16),
               ("Type", np.unicode_, 16),
               ("Min_Price", np.float64),
               ("Price", np.float64),
               ("Max_Price", np.float64),
               ("MPG_city", np.float64),
               ("MPG_highway", np.float64),
               ("AirBags", np.unicode_, 16)])

dt

data = np.genfromtxt('Datasets/cars93.csv', 
                     delimiter=",", 
                     dtype=dt,
                     skip_header=1,
                     usecols=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
data

array([('"Acura"', '"Integra"', '"Small"', 12.9, 15.9, 18.8, 25., 31., '"None"'),
       ('"Acura"', '"Legend"', '"Midsize"', 29.2, 33.9, 38.7, 18., 25., '"Driver & Passen'),
       ('"Audi"', '"90"', '"Compact"', 25.9, 29.1, 32.3, 20., 26., '"Driver only"'),
       ('"Audi"', '"100"', '"Midsize"', 30.8, 37.7, 44.6, 19., 26., '"Driver & Passen'),
       ('"BMW"', '"535i"', '"Midsize"', 23.7, 30. , 36.2, 22., 30., '"Driver only"'),
       ('"Buick"', '"Century"', '"Midsize"', 14.2, 15.7, 17.3, 22., 31., '"Driver only"'),
       ('"Buick"', '"LeSabre"', '"Large"', 19.9, 20.8, 21.7, 19., 28., '"Driver only"'),
       ('"Buick"', '"Roadmaster"', '"Large"', 22.6, 23.7, 24.9, 16., 25., '"Driver only"'),
       ('"Buick"', '"Riviera"', '"Midsize"', 26.3, 26.3, 26.3, 19., 27., '"Driver only"'),
       ('"Cadillac"', '"DeVille"', '"Large"', 33. , 34.7, 36.3, 16., 25., '"Driver only"'),
       ('"Cadillac"', '"Seville"', '"Midsize"', 37.5, 40.1, 42.7, 16., 25., '"Driver & Passen'),
       ('"Che

1. Sort the cars93 dataset based on Price column.


In [ ]:
data[np.argsort(data['Price'])]

2. Sort the cars93 dataset based on two columns : Min_Price column first and Max_Price second.

In [20]:
x = np.lexsort((data['Min_Price'].tolist(), data['Max_Price'].tolist()))

In [ ]:
x

In [ ]:
data[x]

# # OR
# data[np.lexsort((data['Min_Price'].tolist(), data['Max_Price'].tolist()))]

3. Extract various time values from the date 

  <code>today = np.datetime64('2018-08-13T06:25') </code>

In [23]:
today = np.datetime64('2021-09-28T07:30')
print('Year is :', np.datetime64(today,'Y'))
print('Month is :', np.datetime64(today,'M'))
print('Date is :', np.datetime64(today,'D'))
print('Hour is :', np.datetime64(today,'h'))
print('Minute is :', np.datetime64(today,'m'))  # upto here
print('Second is :', np.datetime64(today,'s'))
print('Milli second is :', np.datetime64(today,'ms'))
print('Nano second is :', np.datetime64(today,'ns'))

Year is : 2021
Month is : 2021-09
Date is : 2021-09-28
Hour is : 2021-09-28T07
Minute is : 2021-09-28T07:30
Second is : 2021-09-28T07:30:00
Milli second is : 2021-09-28T07:30:00.000
Nano second is : 2021-09-28T07:30:00.000000000


4. Add 5 business days and regular days to the date

  <code>today = '2018-03-26'</code>

In [25]:
today = '2018-03-26'
np.busday_offset(today, 5)

numpy.datetime64('2018-04-02')

5. Find out the business days between two dates

  <code>day1 = '2021-09-28'</code><br>
  <code>day2 = '2021-10-28'</code>

In [27]:
day1 = '2021-09-28'
day2 = '2021-10-28'
np.busday_count(day1, day2)

22

6. Create a function to compute the coeffecient of variation and apply it row wise in the iris dataset

```
  url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
  iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])
```

In [52]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

def find_COV(x):
  return np.std(x) / np.mean(x)

In [53]:
print("Row wise : \n", np.apply_along_axis(find_COV, 1, arr=iris_2d), end='\n')

Row wise : 
 [0.74017985 0.7427582  0.73612102 0.70470192 0.73234704 0.67788348
 0.69149057 0.72345011 0.70946849 0.7465197  0.74027763 0.69856997
 0.75690065 0.76777664 0.79378967 0.71219535 0.72659059 0.72100045
 0.71383837 0.70354654 0.72458541 0.6864548  0.76920117 0.65224098
 0.66495995 0.72413041 0.67280214 0.73329523 0.74895801 0.69639156
 0.7060915  0.71193855 0.74323252 0.75023165 0.7465197  0.77055175
 0.77763523 0.7465197  0.72076703 0.72971741 0.72831188 0.74077853
 0.71648015 0.63517033 0.64037218 0.71478257 0.70997288 0.71553922
 0.73464127 0.73917036 0.50392714 0.45975439 0.4914498  0.49063249
 0.48956044 0.46696325 0.43623505 0.48826904 0.51179378 0.42693948
 0.5271459  0.44197989 0.5725589  0.47140969 0.46075669 0.49620519
 0.42377283 0.51993146 0.51855985 0.50928103 0.39690269 0.49456478
 0.5        0.50236839 0.50308718 0.4960631  0.51682166 0.46501649
 0.45335558 0.53079024 0.5111071  0.52668762 0.49521936 0.4604441
 0.41247896 0.41426188 0.48153401 0.54000324 0.448

7. Cap the petal length (3rd) column of iris_2d between 3 and 5

```
  # Input
  url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
  iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

```

In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0, 1, 2, 3])

In [58]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [59]:
# Clip petallength 
np.clip(iris_2d[:,2], 3, 5)

array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5. , 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 5. , 5. , 5. , 5. ,
       5. , 5. , 4.5, 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 4.9, 5. , 4.9, 5. , 5. , 4.8, 4.9, 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5. , 5. , 4.8, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5. ])

8. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:

<code>
 < 3 -> 'small' <br>
 3-5 -> 'medium'<br>
 >=5 -> 'large' <br>
</code>


Input: <br> <br>
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br>
iris = np.genfromtxt(url, delimiter=',', dtype='object') <br>
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [61]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [63]:
# Solution

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])